var overview = [
  {
    title: 'Design Tools',
    count: '5+',
    categories: ['art', 'design', 'photo edit'],
  },
  {
    title: 'Tech Stacks',
    count: '20+',
    categories: [
      'languages',
      'frameworks',
      'libraries',
      'unit testing',
      'docs',
      'dev tools',
      'pkg managers',
      'IDE',
      'Utility',
    ],
  },
  {
    title: 'Experience',
    count: '13+',
    categories: ['infosys', 'skava', 'astute', 'cyber web'],
  },
  {
    title: 'Awards',
    count: '8+',
    categories: ['star', 'best employee', 'distinguised'],
  },
  {
    title: 'Own Libraries/Tools',
    count: '14+',
    categories: ['automation', 'product', 'js libs', 'tools'],
  },
  {
    title: 'Works',
    count: '50+',
    categories: ['art', 'designs', '2D'],
  },
]

const designTools = [
  {
    title: 'Photoshop',
    url: 'logo_ps.jpg',
  },
  {
    title: 'XD',
    url: 'logo_xd.png',
  },
  {
    title: 'Sketch',
    url: 'logo_sketch.jpg',
  },
  {
    title: 'Flash',
    url: 'logo_flash.jpg',
  },
  {
    title: 'Autodesk',
    url: 'logo_autodesk.png',
  },
  {
    title: 'Lightroom',
    url: 'logo_lr.png',
  },
]

const techStacks = {
  languages: [
    { url: 'logo_html.png', title: 'HTML' },
    { url: 'logo_css.png', title: 'CSS' },
    { url: 'logo_js.jpeg', title: 'JS/ES5' },
    { url: 'logo_es6.jpg', title: 'JS/ES6+' },
    { url: 'logo_ts.jpg', title: 'Typescript' },
    { url: 'logo_nodejs.png', title: 'NodeJS' },
    { url: 'logo_ftl.jpg', title: 'FTL' },
    { url: 'logo_xml.png', title: 'XML' },
    { url: 'logo_hb.png', title: 'Handlebars' },
    { url: 'logo_graphql.png', title: 'GraphQL' },
    { url: 'logo_md.png', title: 'Markdown' },
    { url: 'logo_sass.png', title: 'SASS' },
    { url: 'logo_yaml.png', title: 'YAML' },
    { url: 'logo_as3.png', title: 'AS3' },
  ],
  frameworks: [
    { url: 'logo_cra.png', title: 'CRA' },
    { url: 'logo_nextjs.png', title: 'Next.js ' },
    { url: 'logo_mui.png', title: 'Material UI' },
    { url: 'logo_mdbreact.png', title: 'MDB React' },
    { url: 'logo_reactbootstrap.png', title: 'React Bootstrap' },
  ],
  libraries: [
    { url: 'logo_react.png', title: 'React' },
    { url: 'logo_redux.png', title: 'Redux' },
    { url: 'logo_mobx.png', title: 'Mobx' },
    { url: 'logo_styledcomp.png', title: 'Styled Components' },
    { url: 'logo_webpack.png', title: 'Webpack' },
    { url: 'logo_rollup.jpg', title: 'Rollup' },
    { url: 'logo_jquery.jpg', title: 'jQuery' },
    { url: 'logo_jquery_ui.png', title: 'jQuery UI' },
    { url: 'logo_expressjs.png', title: 'Express.js' },
    { url: 'logo_apollo.png', title: 'Apollo Link State' },
  ],
  unittesting: [
    { url: 'logo_jest.png', title: 'Jest' },
    { url: 'logo_cypress.webp', title: 'Cypress' },
    { url: 'logo_puppeteer.png', title: 'Puppeteer' },
    { url: 'logo_rtl.png', title: 'React Testing Library' },
  ],
  docs: [
    { url: 'logo_docsify.png', title: 'Docsify' },
    { url: 'logo_md.png', title: 'Markdown' },
    { url: 'logo_jsdoc3.png', title: 'JS Docs' },
  ],
  devtools: [
    { url: 'logo_git.png', title: 'GIT' },
    { url: 'logo_babel.png', title: 'Babel' },
    { url: 'logo_prettier.jpg', title: 'Prettier' },
    { url: 'logo_editorconfig.png', title: 'Editor Config' },
    { url: 'logo_make.png', title: 'Make' },
    { url: 'logo_eslint.jpg', title: 'ES Lint' },
    { url: 'logo_tslint.png', title: 'TS Lint' },
    { url: 'logo_sonarlint.png', title: 'Sonar Lint' },
    { url: 'logo_storybook.png', title: 'Storybook' },
  ],
  packagemanagers: [
    { url: 'logo_yarn.jpg', title: 'Yarn' },
    { url: 'logo_npm.png', title: 'NPM' },
    { url: 'logo_verdaccio.jpg', title: 'Verdaccio' },
    { url: 'logo_lerna.jpg', title: 'Lerna' },
  ],
}

const businessTools = {
  ide: [
    { url: 'logo_vs.png', title: 'VS Code' },
    { url: 'logo_sublime.jpg', title: 'Sublime' },
    { url: 'logo_eclipse.png', title: 'Eclipse' },
    { url: 'logo_notepad.png', title: 'Notepad++' },
  ],
  utility: [
    { url: 'logo_codesandbox.png', title: 'Code sandbox' },
    { url: 'logo_jira.jpg', title: 'JIRA' },
    { url: 'logo_confluence.jpg', title: 'Confluence' },
    { url: 'logo_trello.jpg', title: 'Trello' },
    { url: 'logo_gitlab.png', title: 'GitLab' },
    { url: 'logo_gdrive.jpg', title: 'G Drive' },
    { url: 'logo_bitbucket.jpg', title: 'Bitbucket' },
    { url: 'logo_tortoisegit.jpg', title: 'Tortoise Git' },
    { url: 'logo_tower.png', title: 'Tower' },
    { url: 'logo_github.png', title: 'Git Hub' },
    { url: 'logo_sourcetree.png', title: 'Source Tree' },
  ],
}

const experience = [
  {
    id: 'infosys',
    company: 'Infosys, Coimbatore',
    url: 'logo_infy.jpg',
    role: 'Creative Manager and Sr. Dev Lead',
    duration: 'From Aug 2020 to Till Date (7months+)',
    responsibilities: [
      'Leading a small development team (9 members) to create interactive and dynamic web applications for the business.',
      'Technology Stack: React JS with Hooks, Typescript, HTML5, CSS3, JavaScript (ES6+), Next.js, Material Bootstrap, Express.js, i18next, Webpack, Storybook, Docsify, Lints, etc.,',
      'Creating the Build system for web app development, CICD Integrations for Dev, UAT, PDN environments & configuration setups',
      'Having Daily standup meeting with team, peer programming and live coding',
      'Tech stacks training to the team',
      'Building automation tools for reducing the dev efforts',
      'Designs & prototype reviews',
      'Gathering Software requirements, design and develop',
      'Elicit requirements from BA team and executing in Agile sprints',
      'Developing iterative functionality/prototypes based on requirements',
      'Application development using MDBReact, ReactJS, State management with Hooks,Typescript and Next.Js',
      'Identify design alternatives and conduct technical feasibility',
      'Solving Technical Issues',
      'Creating Flow diagrams, architecture diagrams, documentations etc.,',
      'Driving team which includes from fresh college grads to experienced laterals',
      'Building UI/UX components based on the Atomic Design Methodology.',
    ],
    clients: [],
  },
  {
    id: 'skava',
    company: 'Skava an Infosys, Coimbatore',
    url: 'logo_skava.png',
    role: 'Creative Manager and Sr. Dev Lead',
    duration: 'From March 2009 to Aug 2020',
    responsibilities: [
      'Leading a small development team to create interactive and dynamic web applications for the business.',
      'Technology Stack: React JS with Hooks, Typescript, HTML5, CSS3, JavaScript (ES6+), Next.js, Material Bootstrap, ExpressJs, i18next, Webpack, Storybook, Docsify, Lints, etc.,',
      'Creating the Build system for web App development, CICD Integrations, Dev and PDN deployment configuration setups',
      'Having Daily standup meeting with team, peer programming and live coding',
      'Creating the mobile/tablet web/app UI designs based on the customer needs',
      'Creating the wireframes',
      'Creating the design & video presentation for multiple products to promote them for sales perspective.',
      'Tech stacks training to the team',
      'Building automation tools for reducing the dev efforts',
      'Designs & prototype reviews',
      'Gathering Software requirements, design and develop',
      'Elicit requirements from BA team and executing in Agile sprints',
      'Developing iterative functionality/prototypes based on requirements ',
      'Application development using MDBReact, ReactJS, State management with Hooks, Typescript and Next.Js',
      'Identify design alternatives and conduct technical feasibility',
      'Solving Technical Issues',
      'Driving team which includes from fresh college grads to experienced laterals ',
      'Building UI/UX components based on the Atomic Design Methodology.',
    ],
    clients: [],
  },
  {
    id: 'astute',
    company: 'Astute IT Service India pvt ltd., Erode.',
    url: 'logo_skava.png',
    role: 'Flash Animator',
    duration: 'From Oct 2007 to September 2008',
    responsibilities: [
      'Creating the 2D animations for Business Ads',
      'Character designing rigging & animations for multiple games',
      'Creating 2D user interactive presentations',
      'Creating Posters, web designs for web applications',
    ],
    clients: [],
  },
  {
    id: 'cws',
    company: 'Cyber Web Service, Coimbatore.',
    url: 'logo_cws.jpg',
    role: 'Trainee Designer',
    duration: 'From May 2007 to July 2007',
    responsibilities: [
      'Creating the 2D animations for Business Ads',
      'Creating 2D user interactive presentations',
      'Creating Posters, web designs for web applications',
    ],
    clients: [],
  },
]
